-- Seeds for currencies
INSERT OR IGNORE INTO currencies (code, symbol, name) VALUES
('AED', 'AED', 'United Arab Emirates Dirham'),
('AFN', 'Af', 'Afghan Afghani'),
('ALL', 'ALL', 'Albanian Lek'),
('AMD', 'AMD', 'Armenian Dram'),
('ARS', 'AR$', 'Argentine Peso'),
('AUD', 'AU$', 'Australian Dollar'),
('AZN', 'man.', 'Azerbaijani Manat'),
('BAM', 'KM', 'Bosnia-Herzegovina Convertible Mark'),
('BDT', 'Tk', 'Bangladeshi Taka'),
('BGN', 'BGN', 'Bulgarian Lev'),
('BHD', 'BD', 'Bahraini Dinar'),
('BIF', 'FBu', 'Burundian Franc'),
('BND', 'BN$', 'Brunei Dollar'),
('BOB', 'Bs', 'Bolivian Boliviano'),
('BRL', 'R$', 'Brazilian Real'),
('BWP', 'BWP', 'Botswanan Pula'),
('BYN', 'Br', 'Belarusian Ruble'),
('BZD', 'BZ$', 'Belize Dollar'),
('CAD', 'CA$', 'Canadian Dollar'),
('CDF', 'CDF', 'Congolese Franc'),
('CHF', 'CHF', 'Swiss Franc'),
('CLP', 'CL$', 'Chilean Peso'),
('CNY', 'CN¥', 'Chinese Yuan'),
('COP', 'CO$', 'Colombian Peso'),
('CRC', '₡', 'Costa Rican Colón'),
('CVE', 'CV$', 'Cape Verdean Escudo'),
('CZK', 'Kč', 'Czech Republic Koruna'),
('DJF', 'Fdj', 'Djiboutian Franc'),
('DKK', 'Dkr', 'Danish Krone'),
('DOP', 'RD$', 'Dominican Peso'),
('DZD', 'DA', 'Algerian Dinar'),
('EEK', 'Ekr', 'Estonian Kroon'),
('EGP', 'EGP', 'Egyptian Pound'),
('ERN', 'Nfk', 'Eritrean Nakfa'),
('ETB', 'Br', 'Ethiopian Birr'),
('EUR', '€', 'Euro'),
('GBP', '£', 'British Pound Sterling'),
('GEL', 'GEL', 'Georgian Lari'),
('GHS', 'GH₵', 'Ghanaian Cedi'),
('GNF', 'FG', 'Guinean Franc'),
('GTQ', 'GTQ', 'Guatemalan Quetzal'),
('HKD', 'HK$', 'Hong Kong Dollar'),
('HNL', 'HNL', 'Honduran Lempira'),
('HRK', 'kn', 'Croatian Kuna'),
('HUF', 'Ft', 'Hungarian Forint'),
('IDR', 'Rp', 'Indonesian Rupiah'),
('ILS', '₪', 'Israeli New Sheqel'),
('INR', 'Rs', 'Indian Rupee'),
('IQD', 'IQD', 'Iraqi Dinar'),
('IRR', 'IRR', 'Iranian Rial'),
('ISK', 'Ikr', 'Icelandic Króna'),
('JMD', 'J$', 'Jamaican Dollar'),
('JOD', 'JD', 'Jordanian Dinar'),
('JPY', '¥', 'Japanese Yen'),
('KES', 'Ksh', 'Kenyan Shilling'),
('KHR', 'KHR', 'Cambodian Riel'),
('KMF', 'CF', 'Comorian Franc'),
('KRW', '₩', 'South Korean Won'),
('KWD', 'KD', 'Kuwaiti Dinar'),
('KZT', 'KZT', 'Kazakhstani Tenge'),
('LBP', 'L.L.', 'Lebanese Pound'),
('LKR', 'SLRs', 'Sri Lankan Rupee'),
('LTL', 'Lt', 'Lithuanian Litas'),
('LVL', 'Ls', 'Latvian Lats'),
('LYD', 'LD', 'Libyan Dinar'),
('MAD', 'MAD', 'Moroccan Dirham'),
('MDL', 'MDL', 'Moldovan Leu'),
('MGA', 'MGA', 'Malagasy Ariary'),
('MKD', 'MKD', 'Macedonian Denar'),
('MMK', 'MMK', 'Myanma Kyat'),
('MOP', 'MOP$', 'Macanese Pataca'),
('MUR', 'MURs', 'Mauritian Rupee'),
('MXN', 'MX$', 'Mexican Peso'),
('MYR', 'RM', 'Malaysian Ringgit'),
('MZN', 'MTn', 'Mozambican Metical'),
('NAD', 'N$', 'Namibian Dollar'),
('NGN', '₦', 'Nigerian Naira'),
('NIO', 'C$', 'Nicaraguan Córdoba'),
('NOK', 'Nkr', 'Norwegian Krone'),
('NPR', 'NPRs', 'Nepalese Rupee'),
('NZD', 'NZ$', 'New Zealand Dollar'),
('OMR', 'OMR', 'Omani Rial'),
('PAB', 'B/.', 'Panamanian Balboa'),
('PEN', 'S/.', 'Peruvian Nuevo Sol'),
('PHP', '₱', 'Philippine Peso'),
('PKR', 'PKRs', 'Pakistani Rupee'),
('PLN', 'zł', 'Polish Zloty'),
('PYG', '₲', 'Paraguayan Guarani'),
('QAR', 'QR', 'Qatari Rial'),
('RON', 'RON', 'Romanian Leu'),
('RSD', 'din.', 'Serbian Dinar'),
('RUB', 'RUB', 'Russian Ruble'),
('RWF', 'RWF', 'Rwandan Franc'),
('SAR', 'SR', 'Saudi Riyal'),
('SDG', 'SDG', 'Sudanese Pound'),
('SEK', 'Skr', 'Swedish Krona'),
('SGD', 'S$', 'Singapore Dollar'),
('SOS', 'Ssh', 'Somali Shilling'),
('SYP', 'SY£', 'Syrian Pound'),
('THB', '฿', 'Thai Baht'),
('TND', 'DT', 'Tunisian Dinar'),
('TOP', 'T$', 'Tongan Paʻanga'),
('TRY', 'TL', 'Turkish Lira'),
('TTD', 'TT$', 'Trinidad and Tobago Dollar'),
('TWD', 'NT$', 'New Taiwan Dollar'),
('TZS', 'TSh', 'Tanzanian Shilling'),
('UAH', '₴', 'Ukrainian Hryvnia'),
('UGX', 'USh', 'Ugandan Shilling'),
('USD', '$', 'US Dollar'),
('UYU', '$U', 'Uruguayan Peso'),
('UZS', 'UZS', 'Uzbekistan Som'),
('VEF', 'Bs.F.', 'Venezuelan Bolívar'),
('VND', '₫', 'Vietnamese Dong'),
('XAF', 'FCFA', 'CFA Franc BEAC'),
('XOF', 'CFA', 'CFA Franc BCEAO'),
('YER', 'YR', 'Yemeni Rial'),
('ZAR', 'R', 'South African Rand'),
('ZMK', 'ZK', 'Zambian Kwacha'),
('ZWL', 'ZWL$', 'Zimbabwean Dollar');


INSERT OR IGNORE INTO languages (code, name, icon) VALUES
('en', 'English', '🇬🇧'),
('de', 'Deutsch', '🇩🇪'),
('ua', 'Українська', '🇺🇦'),
('cr', 'Qırım', '💙');


INSERT OR IGNORE INTO account_types (code, name, description) VALUES
    ('CASH', 'Cash', 'Physical cash holdings'),
    ('BANK_CHK', 'Checking Account', 'Standard checking/current account'),
    ('BANK_SAV', 'Savings Account', 'Standard savings account'),
    ('CARD_CR', 'Credit Card', 'Standard credit card'),
    ('CARD_DB', 'Debit Card Account', 'Account linked to a debit card (often checking)'),
    ('INVEST', 'Investment', 'Investment or brokerage account'),
    ('LOAN', 'Loan Account', 'Mortgage, car loan, etc.'),
    ('EWALLET', 'E-Wallet', 'Digital wallet like PayPal, Venmo');
